# GET http://localhost:4000/search?username=qEZPZ


GET http://localhost:4000/users
###




POST http://localhost:4000/addPlayer
Content-Type: application/json

{
    "username": "qEZPZ",
    "info": "info"
}
###

PATCH http://localhost:4000/updatePlayerInfo
Content-Type: application/json

{
    "username": "qEZPZ",
    "newStatus": "YEAHHH"
}

###

DELETE http://localhost:4000/delete
Content-Type: application/json

{
    "username": "qEZPZ"
}



POST http://localhost:4000/